export const metadata = { title: 'Disclaimer' };

export default function DisclaimerPage() {
  return (
    <article className="max-w-2xl mx-auto px-4 py-10 prose-cac">
      <h1>Disclaimer</h1>
      <p><strong>Last updated:</strong> {new Date().toISOString().slice(0, 10)}</p>

      <h2>Not a government site</h2>
      <p>
        CAC.help is an independent, privately-operated website. It is <strong>not</strong> affiliated with, endorsed by, sponsored by,
        or operated by the United States Department of Defense (DoD), the United States Government, any branch of the U.S. Armed Forces,
        the Defense Information Systems Agency (DISA), the Defense Manpower Data Center (DMDC), or any federal, state, or local agency.
      </p>
      <p>
        "Common Access Card," "CAC," "DoD," and the names of branches of the U.S. Armed Forces are trademarks or service marks of
        their respective owners, used here for descriptive purposes only.
      </p>

      <h2>No warranty</h2>
      <p>
        Information provided on CAC.help is offered "as-is" without warranty of any kind, express or implied. We make a good-faith effort
        to keep our guidance accurate, but operating systems, browsers, DoD policies, and middleware change frequently. We cannot guarantee
        that any procedure described here will work for your specific configuration.
      </p>

      <h2>Not professional advice</h2>
      <p>
        Content on CAC.help is for general informational purposes. It is not a substitute for guidance from your unit's IT support,
        your service's official help desk, your information assurance officer, or any other authoritative source. When in doubt,
        defer to your organization's official IT policy.
      </p>

      <h2>AI-generated content</h2>
      <p>
        Responses from the CAC.help AI assistant are generated by a large language model (Anthropic Claude). While we provide curated
        knowledge to ground the model, AI responses can contain errors. Verify critical procedures with an authoritative source before
        acting, especially anything involving registry edits, system services, or certificate trust changes.
      </p>

      <h2>Security</h2>
      <p>
        <strong>Never share your CAC PIN with CAC.help or any other website.</strong> No legitimate IT support will ever ask for your CAC PIN.
        We do not collect, store, or transmit CAC PINs.
      </p>

      <h2>External links</h2>
      <p>
        CAC.help may link to third-party websites (DoD Cyber Exchange, vendor sites, community forums). We are not responsible for
        the content, accuracy, or availability of external sites. Linking does not imply endorsement.
      </p>

      <h2>Limitation of liability</h2>
      <p>
        To the maximum extent permitted by law, CAC.help and its operators are not liable for any damages — direct, indirect, incidental,
        consequential, or punitive — arising from your use of this site, including but not limited to lost data, lost time,
        denied access to systems, or hardware damage.
      </p>
    </article>
  );
}
